-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemBuildingTemplate', {
	'Group', "MPT_MapPlacement",
	'Id', "MPT_Place_Water",
	'SaveIn', "Mod/Mde5tLv",
	'mod_handle', 2,
	'object_class', "MPT_PlacementBuilding",
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'can_refab', false,
	'display_name', T(0, --[[ModItemBuildingTemplate MPT_Place_Water display_name]] "Water Deposit"),
	'display_name_pl', T(0, --[[ModItemBuildingTemplate MPT_Place_Water display_name_pl]] "Water Deposits"),
	'description', T(0, --[[ModItemBuildingTemplate MPT_Place_Water description]] "Place a subsurface Water deposit."),
	'build_category', "MPT_MapPlacement",
	'display_icon', "Mod/Mde5tLv/UI/MapPlacement/water.png",
	'build_pos', 2,
	'entity', "SensorTower",
})

