-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemBuildingTemplate', {
	'Group', "MPT_MapPlacement",
	'Id', "MPT_Place_Concrete",
	'SaveIn', "Mod/Mde5tLv",
	'mod_handle', 1,
	'object_class', "MPT_PlacementBuilding",
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'can_refab', false,
	'display_name', T(0, --[[ModItemBuildingTemplate MPT_Place_Concrete display_name]] "Concrete Deposit"),
	'display_name_pl', T(0, --[[ModItemBuildingTemplate MPT_Place_Concrete display_name_pl]] "Concrete Deposits"),
	'description', T(0, --[[ModItemBuildingTemplate MPT_Place_Concrete description]] "Place a mineable Concrete deposit."),
	'build_category', "MPT_MapPlacement",
	'display_icon', "Mod/Mde5tLv/UI/MapPlacement/concrete.png",
	'entity', "SensorTower",
})

