-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemBuildingTemplate', {
	'Group', "MPT_MapPlacement",
	'Id', "MPT_Place_ExoticMinerals",
	'SaveIn', "Mod/Mde5tLv",
	'mod_handle', 5,
	'object_class', "MPT_PlacementBuilding",
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'can_refab', false,
	'display_name', T(0, --[[ModItemBuildingTemplate MPT_Place_ExoticMinerals display_name]] "Exotic Minerals Deposit"),
	'display_name_pl', T(0, --[[ModItemBuildingTemplate MPT_Place_ExoticMinerals display_name_pl]] "Exotic Minerals Deposits"),
	'description', T(0, --[[ModItemBuildingTemplate MPT_Place_ExoticMinerals description]] "Place a subsurface Exotic Minerals deposit."),
	'build_category', "MPT_MapPlacement",
	'display_icon', "Mod/Mde5tLv/UI/MapPlacement/exotic_minerals.png",
	'build_pos', 5,
	'entity', "SensorTower",
})

