-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemBuildingTemplate', {
	'Group', "MPT_MapPlacement",
	'Id', "MPT_Place_ResearchAnomaly",
	'SaveIn', "Mod/Mde5tLv",
	'mod_handle', 6,
	'object_class', "MPT_PlacementBuilding",
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'can_refab', false,
	'display_name', T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchAnomaly display_name]] "Research Anomaly"),
	'display_name_pl', T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchAnomaly display_name_pl]] "Research Anomalies"),
	'description', T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchAnomaly description]] "Place an anomaly that grants research when analyzed."),
	'build_category', "MPT_MapPlacement",
	'display_icon', "Mod/Mde5tLv/UI/MapPlacement/anomaly_research.png",
	'build_pos', 10,
	'entity', "SensorTower",
})

