-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemBuildingTemplate', {
	'Group', "MPT_MapPlacement",
	'Id', "MPT_Place_RareMetals",
	'SaveIn', "Mod/Mde5tLv",
	'mod_handle', 4,
	'object_class', "MPT_PlacementBuilding",
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'can_refab', false,
	'display_name', T(0, --[[ModItemBuildingTemplate MPT_Place_RareMetals display_name]] "Rare Metals Deposit"),
	'display_name_pl', T(0, --[[ModItemBuildingTemplate MPT_Place_RareMetals display_name_pl]] "Rare Metals Deposits"),
	'description', T(0, --[[ModItemBuildingTemplate MPT_Place_RareMetals description]] "Place a subsurface Rare Metals deposit."),
	'build_category', "MPT_MapPlacement",
	'display_icon', "Mod/Mde5tLv/UI/MapPlacement/rare_metals.png",
	'build_pos', 4,
	'entity', "SensorTower",
})

