-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_Vista')
DefineClass.MPT_Place_Vista = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 10,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_Vista display_name]] "Vista"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_Vista display_name_pl]] "Vistas"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_Vista description]] "Place a Vista map bonus."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/vista.png",
	build_pos = 20,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

