-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_ResearchSite')
DefineClass.MPT_Place_ResearchSite = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 11,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchSite display_name]] "Research Site"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchSite display_name_pl]] "Research Sites"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_ResearchSite description]] "Place a Research Site map bonus."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/research_site.png",
	build_pos = 21,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

