-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_Metals')
DefineClass.MPT_Place_Metals = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 3,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_Metals display_name]] "Metals Deposit"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_Metals display_name_pl]] "Metals Deposits"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_Metals description]] "Place a subsurface Metals deposit."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/metals.png",
	build_pos = 3,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

