-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_ResourceAnomaly')
DefineClass.MPT_Place_ResourceAnomaly = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 9,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_ResourceAnomaly display_name]] "Resource Anomaly"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_ResourceAnomaly display_name_pl]] "Resource Anomalies"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_ResourceAnomaly description]] "Place a resource anomaly."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/anomaly_resource.png",
	build_pos = 13,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

