-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_TechAnomaly')
DefineClass.MPT_Place_TechAnomaly = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 7,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_TechAnomaly display_name]] "Technology Anomaly"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_TechAnomaly display_name_pl]] "Technology Anomalies"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_TechAnomaly description]] "Place an anomaly that unlocks technology when analyzed."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/anomaly_tech.png",
	build_pos = 11,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

