-- ========== GENERATED BY BuildingTemplate Editor (Ctrl-Alt-B) DO NOT EDIT MANUALLY! ==========

UndefineClass('MPT_Place_BreakthroughAnomaly')
DefineClass.MPT_Place_BreakthroughAnomaly = {
	__parents = { "MPT_PlacementBuilding" },
	__generated_by_class = "ModItemBuildingTemplate",


	mod_handle = 8,
	object_class = "MPT_PlacementBuilding",
	build_points = 0,
	instant_build = true,
	dome_forbidden = true,
	can_refab = false,
	display_name = T(0, --[[ModItemBuildingTemplate MPT_Place_BreakthroughAnomaly display_name]] "Breakthrough Anomaly"),
	display_name_pl = T(0, --[[ModItemBuildingTemplate MPT_Place_BreakthroughAnomaly display_name_pl]] "Breakthrough Anomalies"),
	description = T(0, --[[ModItemBuildingTemplate MPT_Place_BreakthroughAnomaly description]] "Place a Breakthrough anomaly."),
	build_category = "MPT_MapPlacement",
	display_icon = "Mod/Mde5tLv/UI/MapPlacement/anomaly_breakthrough.png",
	build_pos = 12,
	entity = "SensorTower",
	persist_baseclass = "MPT_PlacementBuilding"}

