return {
	PlaceObj('ModItemCode', {
		'CodeFileName', "Code/Script.lua",
	}),

	PlaceObj('ModItemBuildMenuSubcategory', {
		'build_pos', 99,
		'category', "Storages",
		'category_name', "MPT_MapPlacement",
		'description', T(0, "Place deposits, anomalies, Vistas, and Research Sites directly on the map."),
		'display_name', T(0, "Map Placement"),
		'group', "Default",
		'icon', "UI/Icons/Buildings/res_all.tga",
		'id', "MPT_MapPlacement",
	}),

	-- RESOURCE DEPOSITS
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_Concrete",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Concrete Deposit"),
		'display_name_pl', T(0, "Concrete Deposits"),
		'description', T(0, "Place a mineable Concrete deposit."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/res_all.tga",
		'build_pos', 1,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_Water",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Water Deposit"),
		'display_name_pl', T(0, "Water Deposits"),
		'description', T(0, "Place a subsurface Water deposit."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/res_all.tga",
		'build_pos', 2,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_Metals",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Metals Deposit"),
		'display_name_pl', T(0, "Metals Deposits"),
		'description', T(0, "Place a subsurface Metals deposit."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/res_all.tga",
		'build_pos', 3,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_RareMetals",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Rare Metals Deposit"),
		'display_name_pl', T(0, "Rare Metals Deposits"),
		'description', T(0, "Place a subsurface Rare Metals deposit."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/res_all.tga",
		'build_pos', 4,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_ExoticMinerals",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Exotic Minerals Deposit"),
		'display_name_pl', T(0, "Exotic Minerals Deposits"),
		'description', T(0, "Place a subsurface Exotic Minerals deposit."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/res_all.tga",
		'build_pos', 5,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),

	-- ANOMALIES
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_ResearchAnomaly",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Research Anomaly"),
		'display_name_pl', T(0, "Research Anomalies"),
		'description', T(0, "Place an anomaly that grants research when analyzed."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Anomaly_Research.tga",
		'build_pos', 10,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_TechAnomaly",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Technology Anomaly"),
		'display_name_pl', T(0, "Technology Anomalies"),
		'description', T(0, "Place an anomaly that unlocks technology when analyzed."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Anomaly_Tech.tga",
		'build_pos', 11,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_BreakthroughAnomaly",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Breakthrough Anomaly"),
		'display_name_pl', T(0, "Breakthrough Anomalies"),
		'description', T(0, "Place a Breakthrough anomaly."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Anomaly_Breakthrough.tga",
		'build_pos', 12,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_ResourceAnomaly",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Resource Anomaly"),
		'display_name_pl', T(0, "Resource Anomalies"),
		'description', T(0, "Place a resource-type anomaly."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Anomaly_Event.tga",
		'build_pos', 13,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),

	-- VISTA / RESEARCH SITE
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_Vista",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Vista"),
		'display_name_pl', T(0, "Vistas"),
		'description', T(0, "Place a Vista map bonus."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/dome.tga",
		'build_pos', 20,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
	PlaceObj('ModItemBuildingTemplate', {
		'Group', "MPT_MapPlacement",
		'Id', "MPT_Place_ResearchSite",
		'template_class', "MPT_PlacementBuilding",
		'build_points', 0,
		'instant_build', true,
		'dome_forbidden', true,
		'display_name', T(0, "Research Site"),
		'display_name_pl', T(0, "Research Sites"),
		'description', T(0, "Place a Research Site map bonus."),
		'build_category', "MPT_MapPlacement",
		'display_icon', "UI/Icons/Buildings/research.tga",
		'build_pos', 21,
		'entity', "SensorTower",
		'key_bindable', false,
		'on_off_button', false,
		'prio_button', false,
		'count_as_building', false,
		'indestructible', true,
		'can_rotate_during_placement', false,
	}),
}
