return PlaceObj('ModDef', {
	'title', "Placeable deposits and anomalies",
	'description', "Adds in-game placement tools for resource deposits, anomalies, Vistas, and Research Sites.",
	'short_description', "Adds in-game placement tools for resource deposits, anomalies, Vistas, and Research Sites.",
	'image', "Mod/Mde5tLv/Images/Screenshot_4.png",
	'last_changes', "Added the ability to place down deposits, anomalies, vistas, and research sites",
	'id', "Mde5tLv",
	'author', "Spagbotgames",
	'version_major', 1,
	'version', 14,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'code', {
		"Code/Script.lua",
		"Code/BuildingTemplate/MPT_Place_Concrete.generated.lua",
		"Code/BuildingTemplate/MPT_Place_Water.generated.lua",
		"Code/BuildingTemplate/MPT_Place_Metals.generated.lua",
		"Code/BuildingTemplate/MPT_Place_RareMetals.generated.lua",
		"Code/BuildingTemplate/MPT_Place_ExoticMinerals.generated.lua",
		"Code/BuildingTemplate/MPT_Place_ResearchAnomaly.generated.lua",
		"Code/BuildingTemplate/MPT_Place_TechAnomaly.generated.lua",
		"Code/BuildingTemplate/MPT_Place_BreakthroughAnomaly.generated.lua",
		"Code/BuildingTemplate/MPT_Place_ResourceAnomaly.generated.lua",
		"Code/BuildingTemplate/MPT_Place_Vista.generated.lua",
		"Code/BuildingTemplate/MPT_Place_ResearchSite.generated.lua",
	},
	'has_data', true,
	'saved', 1787343279,
	'code_hash', 6620236897179512974,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_Concrete",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_Water",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_Metals",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_RareMetals",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_ExoticMinerals",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_ResearchAnomaly",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_TechAnomaly",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_BreakthroughAnomaly",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_ResourceAnomaly",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_Vista",
			'ClassDisplayName', "BuildingTemplate",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BuildingTemplate",
			'Id', "MPT_Place_ResearchSite",
			'ClassDisplayName', "BuildingTemplate",
		}),
	},
	'pdx_id', 156169,
	'pdx_version', "1",
	'steam_id', "3787619783",
	'TagBuildings', true,
	'TagTools', true,
})